language: node_js
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
after_success:
    - cat ./test/coverage/lcov.info | codacy-coverage --token CODACY_PROJECT_TOKEN && rm -rf ./test/coverage
node_js:
    - 'node'
install:
    - yarn
cache:
    yarn: true
    directories:
        - node_modules
script:
    - yarn test
